name: Deploy single page to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master  # default branch
      - actions # branch where actions are tested

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Pug.js CLI
        run: npm install -g pug-cli
      - name: Make
        run: make dist
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site/'
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2

